In [1]:
from hrl4in.utils.utils import *
from gibson2.utils.utils import rotate_vector_3d
import numpy as np 

INFO:root:Importing iGibson (gibson2 module)
INFO:root:Assets path: /home/vkmittal14/WORKSPACE/TUD/vk_igibson/iGibson/gibson2/data/assets
INFO:root:Gibson Dataset path: /home/vkmittal14/WORKSPACE/TUD/vk_igibson/iGibson/gibson2/data/g_dataset
INFO:root:iG Dataset path: /home/vkmittal14/WORKSPACE/TUD/vk_igibson/iGibson/gibson2/data/ig_dataset
INFO:root:3D-FRONT Dataset path: /home/vkmittal14/WORKSPACE/TUD/vk_igibson/iGibson/gibson2/data/threedfront_dataset
INFO:root:CubiCasa5K Dataset path: /home/vkmittal14/WORKSPACE/TUD/vk_igibson/iGibson/gibson2/data/cubicasa_dataset
INFO:root:Example path: /home/vkmittal14/WORKSPACE/TUD/vk_igibson/iGibson/gibson2/examples
INFO:root:Example config path: /home/vkmittal14/WORKSPACE/TUD/vk_igibson/iGibson/gibson2/examples/configs


In [2]:
vector =  torch.tensor([1.22,2.5,0.6])

In [3]:
vectort = vector.view(1, -1)

In [4]:
r, p, y = 1.5,1.2,1.0

In [5]:
rt = torch.tensor(1.5).view(1, -1)*np.pi
pt = torch.tensor(1.2).view(1, -1)*np.pi
yt = torch.tensor(1.0).view(1, -1)*np.pi

In [6]:
vectort

tensor([[1.2200, 2.5000, 0.6000]])

In [7]:
rotate_vector_3d(vector, r, p, y)

array([ 0.4419153 ,  2.80843041, -0.1258158 ])

In [8]:
rotate_torch_vector(vectort, rt, pt, yt)

tensor([[-0.4825,  0.6000, -2.7396]])