In [1]:
import torch 
import gibson2 
import numpy as np
from gibson2.envs.igibson_env import iGibsonEnv
from gibson2.envs.parallel_env import ParallelNavEnv

INFO:root:Importing iGibson (gibson2 module)
INFO:root:Assets path: /home/vkmittal14/WORKSPACE/TUD/vk_igibson/iGibson/gibson2/data/assets
INFO:root:Gibson Dataset path: /home/vkmittal14/WORKSPACE/TUD/vk_igibson/iGibson/gibson2/data/g_dataset
INFO:root:iG Dataset path: /home/vkmittal14/WORKSPACE/TUD/vk_igibson/iGibson/gibson2/data/ig_dataset
INFO:root:3D-FRONT Dataset path: /home/vkmittal14/WORKSPACE/TUD/vk_igibson/iGibson/gibson2/data/threedfront_dataset
INFO:root:CubiCasa5K Dataset path: /home/vkmittal14/WORKSPACE/TUD/vk_igibson/iGibson/gibson2/data/cubicasa_dataset
INFO:root:Example path: /home/vkmittal14/WORKSPACE/TUD/vk_igibson/iGibson/gibson2/examples
INFO:root:Example config path: /home/vkmittal14/WORKSPACE/TUD/vk_igibson/iGibson/gibson2/examples/configs


In [2]:
def load_env(env_mode, device_idx):
    return iGibsonEnv(
    config_file= "../configs/tiago_stadium_point_nav_random.yaml", 
    mode = "headless", 
    action_timestep=1.0/10.0, 
    physics_timestep=1.0/40.0,
    automatic_reset= True, 
    device_idx= device_idx)

In [3]:
sim_gpu_id = [0]
env_id_to_which_gpu = np.linspace(
        0,
        len(sim_gpu_id),
        num=2,
        dtype=np.int,
        endpoint=False,
    )

/home/vkmittal14/miniconda3/envs/vk-igibson/lib/python3.7/site-packages/ipykernel_launcher.py:6: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


In [4]:
env_id_to_which_gpu

array([0, 0])

In [5]:
train_envs = [
        lambda device_idx=sim_gpu_id[env_id_to_which_gpu[env_id]]: load_env(
            "headless", device_idx
        )
        for env_id in range(1)
    ]

In [6]:
train_envs = ParallelNavEnv(train_envs, blocking=False)

{'build_graph': False,
 'collision_ignore_link_a_ids': [1, 2, 3, 4],
 'collision_reward_weight': 0,
 'depth_high': 3.0,
 'depth_low': 0.35,
 'depth_noise_rate': 0.0,
 'discount_factor': 0.99,
 'dist_tol': 0.5,
 'fisheye': False,
 'goal_format': 'polar',
 'image_height': 128,
 'image_width': 128,
 'initial_pos_z_offset': 0.1,
 'intial_robot_pos': [0, 0, 0],
 'is_discrete': False,
 'laser_angular_range': 240.0,
 'laser_linear_range': 5.6,
 'laser_link_name': 'rgbd_laser_link',
 'load_texture': True,
 'max_collisions_allowed': 500,
 'max_step': 1000,
 'min_laser_dist': 0.05,
 'n_horizontal_rays': 228,
 'n_vertical_beams': 1,
 'object_randomization_freq': None,
 'output': ['task_obs'],
 'potential_reward_weight': 1.0,
 'pybullet_load_texture': True,
 'reward_type': 'l2',
 'robot': 'Tiago_Single',
 'scan_noise_rate': 0.0,
 'scene': 'stadium',
 'success_reward': 10.0,
 'target_dist_max': 5.0,
 'target_dist_min': 1.0,
 'target_visual_object_visible_to_agent': False,
 'task': 'point_nav_random

INFO:root:Device 0 is available for rendering
INFO:root:Command '['/home/vkmittal14/WORKSPACE/TUD/vk_igibson/iGibson/gibson2/render/mesh_renderer/build/test_device', '1']' returned non-zero exit status 1.
INFO:root:Device 1 is not available for rendering
INFO:root:Using device 0 for rendering


******************PyBullet Logging Information:
PyBullet Logging Information******************


INFO:root:Loading /home/vkmittal14/miniconda3/envs/vk-igibson/lib/python3.7/site-packages/pybullet_data/roboschool/models_outdoor/stadium/part0.obj
INFO:root:Loading /home/vkmittal14/miniconda3/envs/vk-igibson/lib/python3.7/site-packages/pybullet_data/roboschool/models_outdoor/stadium/part1.obj
INFO:root:Loading /home/vkmittal14/miniconda3/envs/vk-igibson/lib/python3.7/site-packages/pybullet_data/roboschool/models_outdoor/stadium/part2.obj
INFO:root:Loading robot model file: tiago/tiago_single.urdf
INFO:root:Loading /home/vkmittal14/WORKSPACE/TUD/vk_igibson/iGibson/gibson2/data/assets/models/tiago/pmb2_description/meshes/base/base.stl
INFO:root:Loading /home/vkmittal14/WORKSPACE/TUD/vk_igibson/iGibson/gibson2/data/assets/models/tiago/pmb2_description/meshes/sensors/sick_tim551.stl
INFO:root:Loading /home/vkmittal14/WORKSPACE/TUD/vk_igibson/iGibson/gibson2/data/assets/models/tiago/pmb2_description/meshes/sensors/srf05.stl
INFO:root:Loading /home/vkmittal14/WORKSPACE/TUD/vk_igibson/iGibs

In [7]:
train_envs.reset()

[OrderedDict([('task_obs',
               array([ 2.28551218e-03, -9.05261869e-04,  9.70173861e-05,  2.92067437e-04,
                       6.79189035e-05, -2.30575888e-02,  3.40228957e-05, -2.73100386e-06,
                       3.68629528e-01,  4.65641864e+00,  1.06067014e+00,  0.00000000e+00]))])]

In [8]:
env_id_to_which_gpu

array([0, 0])

In [9]:
train_envs.action_space

Box(-1.0, 1.0, (14,), float32)

In [10]:
# train_envs.act()

In [18]:
import numpy as np
action = np.random.rand(2, 2)

In [19]:
train_envs.step(action)

Exception: Traceback (most recent call last):
  File "/home/vkmittal14/WORKSPACE/TUD/vk_igibson/iGibson/gibson2/envs/parallel_env.py", line 230, in _worker
    result = getattr(env, name)(*args, **kwargs)
  File "/home/vkmittal14/WORKSPACE/TUD/vk_igibson/iGibson/gibson2/envs/igibson_env.py", line 303, in step
    self.robots[0].apply_action(action)
  File "/home/vkmittal14/WORKSPACE/TUD/vk_igibson/iGibson/gibson2/robots/robot_locomotor.py", line 270, in apply_action
    real_action = self.policy_action_to_robot_action(action)
  File "/home/vkmittal14/WORKSPACE/TUD/vk_igibson/iGibson/gibson2/robots/robot_locomotor.py", line 259, in policy_action_to_robot_action
    self.action_space.high)
  File "<__array_function__ internals>", line 6, in clip
  File "/home/vkmittal14/miniconda3/envs/vk-igibson/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 2115, in clip
    return _wrapfunc(a, 'clip', a_min, a_max, out=out, **kwargs)
  File "/home/vkmittal14/miniconda3/envs/vk-igibson/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
  File "/home/vkmittal14/miniconda3/envs/vk-igibson/lib/python3.7/site-packages/numpy/core/_methods.py", line 160, in _clip
    um.clip, a, min, max, out=out, casting=casting, **kwargs)
  File "/home/vkmittal14/miniconda3/envs/vk-igibson/lib/python3.7/site-packages/numpy/core/_methods.py", line 113, in _clip_dep_invoke_with_casting
    return ufunc(*args, out=out, **kwargs)
ValueError: operands could not be broadcast together with shapes (2,) (14,) (14,) 


In [11]:
train_envs._envs[0].config["robot"]

'Tiago_Single'